package hedaox.ninjinentities.entities;

import hedaox.ninjinentities.lib.ModVars;
import cpw.mods.fml.common.registry.EntityRegistry;

public class NinjinEntities {
	public static void init()
	{
		createEntity(EntityMasterBaba.class, 64, ModVars.MOD_ID + ".masterBaba");
		createEntity(EntityBandit1.class, 64, ModVars.MOD_ID + ".bandit1");
		createEntity(EntityGeneralBlue.class, 64, ModVars.MOD_ID + ".generalBlue");
		createEntity(EntityHercule.class, 64, ModVars.MOD_ID + ".hercule");
		createEntity(EntityGohanAdult.class, 64, ModVars.MOD_ID + ".gohanAdult");
		createEntity(EntityGohanAdultSsj.class, 64, ModVars.MOD_ID + ".gohanAdultSsj");
		createEntity(EntityGohanAdultSsj2.class, 64, ModVars.MOD_ID + ".gohanAdultSsj2");
		createEntity(EntityGohanKid1.class, 64, ModVars.MOD_ID + ".gohanKid1");
		createEntity(EntityGohanKid2.class, 64, ModVars.MOD_ID + ".gohanKid2");
		createEntity(EntityGohanKid3.class, 64, ModVars.MOD_ID + ".gohanKid3");
		createEntity(EntityGohanKidArmor.class, 64, ModVars.MOD_ID + ".gohanKidArmor");
		createEntity(EntityGohanTeen.class, 64, ModVars.MOD_ID + ".gohanTeen");
		createEntity(EntityGohanTeenArmor.class, 64, ModVars.MOD_ID + ".gohanTeenArmor");
		createEntity(EntityGohanTeenArmorSsj.class, 64, ModVars.MOD_ID + ".gohanTeenArmorSsj");
		createEntity(EntityGohanTeenSsj.class, 64, ModVars.MOD_ID + ".gohanTeenSsj");
		createEntity(EntityGohanTeenSsj2.class, 64, ModVars.MOD_ID + ".gohanTeenSsj2");
		createEntity(EntityGohanUltimate.class, 64, ModVars.MOD_ID + ".gohanUltimate");
		createEntity(EntityGokuKid1.class, 64, ModVars.MOD_ID + ".gokuKid1");
		createEntity(EntityGokuKid2.class, 64, ModVars.MOD_ID + ".gokuKid2");
		createEntity(EntityGoku1.class, 64, ModVars.MOD_ID + ".goku1");
		createEntity(EntityGoku2Kaioken.class, 64, ModVars.MOD_ID + ".goku2Kaioken");
		createEntity(EntityGoku2.class, 64, ModVars.MOD_ID + ".goku2");
		createEntity(EntityGokuArmor.class, 64, ModVars.MOD_ID + ".gokuArmor");
		createEntity(EntityGokuArmorSsj.class, 64, ModVars.MOD_ID + ".gokuArmorSsj");
		createEntity(EntityGokunoweight.class, 64, ModVars.MOD_ID + ".gokunoweight");
		createEntity(EntityGokuSsj.class, 64, ModVars.MOD_ID + ".gokuSsj");
		createEntity(EntityGokuSsj2.class, 64, ModVars.MOD_ID + ".gokuSsj2");
		createEntity(EntityGokuSsj3.class, 64, ModVars.MOD_ID + ".gokuSsj3");
		createEntity(EntityGokuSsjg.class, 64, ModVars.MOD_ID + ".gokuSsjg");
		createEntity(EntityGokuSsjb.class, 64, ModVars.MOD_ID + ".gokuSsjb");
		createEntity(EntityGokuSuper.class, 64, ModVars.MOD_ID + ".gokuSuper");
		createEntity(EntityGokuSuperSsj.class, 64, ModVars.MOD_ID + ".gokuSuperSsj");
		createEntity(EntityGokuSuperSsjb.class, 64, ModVars.MOD_ID + ".gokuSuperSsjb");
		createEntity(EntityGokuUI.class, 64, ModVars.MOD_ID + ".gokuUi");
		createEntity(EntityGokuUIM.class, 64, ModVars.MOD_ID + ".gokuUiM");
		createEntity(EntityGokuYardrat.class, 64, ModVars.MOD_ID + ".gokuYardrat");
		createEntity(EntityGokuYardratSsj.class, 64, ModVars.MOD_ID + ".gokuYardratSsj");
		createEntity(EntityGoten.class, 64, ModVars.MOD_ID + ".goten");
		createEntity(EntityGotenSsj.class, 64, ModVars.MOD_ID + ".gotenSsj");
		createEntity(EntityGotenks.class, 64, ModVars.MOD_ID + ".gotenks");
		createEntity(EntityGotenksSsj.class, 64, ModVars.MOD_ID + ".gotenksSsj");
		createEntity(EntityGotenksSsj3.class, 64, ModVars.MOD_ID + ".gotenksSsj3");
		createEntity(EntityKrillin1.class, 64, ModVars.MOD_ID + ".krillin1");
		createEntity(EntityKrillin2.class, 64, ModVars.MOD_ID + ".krillin2");
		createEntity(EntityKrillinKid1.class, 64, ModVars.MOD_ID + ".krillinKid1");
		createEntity(EntityKrillinKid2.class, 64, ModVars.MOD_ID + ".krillinKid2");
		createEntity(EntityTien.class, 64, ModVars.MOD_ID + ".tien");
		createEntity(EntityChiaotzu1.class, 64, ModVars.MOD_ID + ".chiaotzu1");
		createEntity(EntityChiaotzu2.class, 64, ModVars.MOD_ID + ".chiaotzu2");
		createEntity(EntityYamcha1.class, 64, ModVars.MOD_ID + ".yamcha1");
		createEntity(EntityYamcha2.class, 64, ModVars.MOD_ID + ".yamcha2");
		createEntity(EntityYamcha3.class, 64, ModVars.MOD_ID + ".yamcha3");
		createEntity(EntityPiccolo.class, 64, ModVars.MOD_ID + ".piccolo");
		createEntity(EntityOozaru.class, 64, ModVars.MOD_ID + ".oozaru");
		createEntity(EntityRoshi.class, 64, ModVars.MOD_ID + ".roshi");
		createEntity(EntityRoshiBuff.class, 64, ModVars.MOD_ID + ".roshiBuff");
		createEntity(EntityTrunksArmor.class, 64, ModVars.MOD_ID + ".trunksArmor");
		createEntity(EntityTrunksArmorSsj.class, 64, ModVars.MOD_ID + ".trunksArmorSsj");
		createEntity(EntityTrunksArmorSsjG2.class, 64, ModVars.MOD_ID + ".trunksArmorSsjG2");
		createEntity(EntityTrunksArmorSsjG3.class, 64, ModVars.MOD_ID + ".trunksArmorSsjG3");
		createEntity(EntityTrunksFutur.class, 64, ModVars.MOD_ID + ".trunksFutur");
		createEntity(EntityTrunksFuturSsj.class, 64, ModVars.MOD_ID + ".trunksFuturSsj");
		createEntity(EntityTrunksFuturSuper.class, 64, ModVars.MOD_ID + ".trunksFuturSuper");
		createEntity(EntityTrunksFuturSuperSsj.class, 64, ModVars.MOD_ID + ".trunksFuturSuperSsj");
		createEntity(EntityTrunksFuturSuperSsj2.class, 64, ModVars.MOD_ID + ".trunksFuturSuperSsj2");
		createEntity(EntityTrunksFuturSuperSsjG3.class, 64, ModVars.MOD_ID + ".trunksFuturSuperSsjG3");
		createEntity(EntityTrunksFuturSuperSsjRage.class, 64, ModVars.MOD_ID + ".trunksFuturSuperSsjRage");
		createEntity(EntityTrunksKid.class, 64, ModVars.MOD_ID + ".trunksKid");
		createEntity(EntityTrunksKidSsj.class, 64, ModVars.MOD_ID + ".trunksKidSsj");
		createEntity(EntityVegeto.class, 64, ModVars.MOD_ID + ".vegeto");
		createEntity(EntityVegetoSsj.class, 64, ModVars.MOD_ID + ".vegetoSsj");
		createEntity(EntityVegetoSsjb.class, 64, ModVars.MOD_ID + ".vegetoSsjb");
		createEntity(EntityGogeta.class, 64, ModVars.MOD_ID + ".gogeta");
		createEntity(EntityGogetaSsj.class, 64, ModVars.MOD_ID + ".gogetaSsj");
		createEntity(EntityGogetaSsjb.class, 64, ModVars.MOD_ID + ".gogetaSsjb");
		createEntity(EntityVegeta0.class, 64, ModVars.MOD_ID + ".vegeta0");
		createEntity(EntityVegeta.class, 64, ModVars.MOD_ID + ".vegeta");
		createEntity(EntityVegeta3.class, 64, ModVars.MOD_ID + ".vegeta3");
		createEntity(EntityVegetaSsj.class, 64, ModVars.MOD_ID + ".vegetaSsj");
		createEntity(EntityVegetaSsjG2.class, 64, ModVars.MOD_ID + ".vegetaSsjG2");
		createEntity(EntityVegeta2.class, 64, ModVars.MOD_ID + ".vegeta2");
		createEntity(EntityVegeta2Ssj.class, 64, ModVars.MOD_ID + ".vegeta2Ssj");
		createEntity(EntityVegeta2Ssj2.class, 64, ModVars.MOD_ID + ".vegeta2Ssj2");
		createEntity(EntityVegetaSsjg.class, 64, ModVars.MOD_ID + ".vegetaSsjg");
		createEntity(EntityVegetaSsjb.class, 64, ModVars.MOD_ID + ".vegetaSsjb");
		createEntity(EntityVegetaSsjbe.class, 64, ModVars.MOD_ID + ".vegetaSsjbe");
		createEntity(EntityVegetaMajin.class, 64, ModVars.MOD_ID + ".vegetaMajin");
		createEntity(EntityVegetaOozaru.class, 64, ModVars.MOD_ID + ".vegetaOozaru");
		createEntity(EntityVegetaCopy.class, 64, ModVars.MOD_ID + ".vegetaCopy");
		createEntity(EntityVegetaBlueCopy.class, 64, ModVars.MOD_ID + ".vegetaBlueCopy");
		createEntity(EntityVegetaSuper.class, 64, ModVars.MOD_ID + ".vegetaSuper");
		createEntity(EntityVegetaSuperSsj.class, 64, ModVars.MOD_ID + ".vegetaSuperSsj");
		createEntity(EntityVegetaSuperSsjb.class, 64, ModVars.MOD_ID + ".vegetaSuperSsjb");
		createEntity(EntityCyborgTaopaipai.class, 64, ModVars.MOD_ID + ".cyborgTaopaipai");
		createEntity(EntityTaopaipai.class, 64, ModVars.MOD_ID + ".taopaipai");
		createEntity(EntityDaimao.class, 64, ModVars.MOD_ID + ".daimao");
		createEntity(EntityHit.class, 64, ModVars.MOD_ID + ".hit");
		createEntity(EntityFrost1.class, 64, ModVars.MOD_ID + ".frost1");
		createEntity(EntityFrost3.class, 64, ModVars.MOD_ID + ".frost3");
		createEntity(EntityFrost4.class, 64, ModVars.MOD_ID + ".frost4");
		createEntity(EntityCaulifla.class, 64, ModVars.MOD_ID + ".caulifla");
		createEntity(EntityCauliflaSsj.class, 64, ModVars.MOD_ID + ".cauliflaSsj");
		createEntity(EntityCauliflaSsj2.class, 64, ModVars.MOD_ID + ".cauliflaSsj2");
		createEntity(EntityKale.class, 64, ModVars.MOD_ID + ".kale");
		createEntity(EntityKaleSsj.class, 64, ModVars.MOD_ID + ".kaleSsj");
		createEntity(EntityKaleSsjL.class, 64, ModVars.MOD_ID + ".kaleSsjL");
		createEntity(EntityKaleSsj2.class, 64, ModVars.MOD_ID + ".kaleSsj2");
		createEntity(EntityMonaka.class, 64, ModVars.MOD_ID + ".monaka");
		createEntity(EntityGokuBlack.class, 64, ModVars.MOD_ID + ".gokuBlack");
		createEntity(EntityGokuBlackSsj.class, 64, ModVars.MOD_ID + ".gokuBlackSsj");
		createEntity(EntityGokuBlackR.class, 64, ModVars.MOD_ID + ".gokuBlackR");
		createEntity(EntityZamasu.class, 64, ModVars.MOD_ID + ".zamasu");
		createEntity(EntityZamasuMerged.class, 64, ModVars.MOD_ID + ".zamasuMerged");
		createEntity(EntityJiren.class, 64, ModVars.MOD_ID + ".jiren");
		createEntity(EntityJirenSuperFullPower.class, 64, ModVars.MOD_ID + ".jirenSuperFullPower");
		createEntity(EntityToppo.class, 64, ModVars.MOD_ID + ".toppo");
		createEntity(EntityToppoGOD.class, 64, ModVars.MOD_ID + ".toppoGOD");
		createEntity(EntityDyspo.class, 64, ModVars.MOD_ID + ".dyspo");
		createEntity(EntityKefla.class, 64, ModVars.MOD_ID + ".kefla");
		createEntity(EntityKeflaSsj.class, 64, ModVars.MOD_ID + ".keflaSsj");
		createEntity(EntityBergamo.class, 64, ModVars.MOD_ID + ".bergamo");
		createEntity(EntityBasil.class, 64, ModVars.MOD_ID + ".basil");
		createEntity(EntityLavender.class, 64, ModVars.MOD_ID + ".lavender");
		createEntity(EntityPilina.class, 64, ModVars.MOD_ID + ".pilina");
		createEntity(EntitySaonel.class, 64, ModVars.MOD_ID + ".saonel");
		createEntity(EntityBrolySuper.class, 64, ModVars.MOD_ID + ".brolySuper");
		createEntity(EntityBrolySuperWrath.class, 64, ModVars.MOD_ID + ".brolySuperWrath");
		createEntity(EntityBrolySuperSsj.class, 64, ModVars.MOD_ID + ".brolySuperSsj");
		createEntity(EntityBrolySuperSsjL.class, 64, ModVars.MOD_ID + ".brolySuperSsjL");
		createEntity(EntityZarbon1.class, 64, ModVars.MOD_ID + ".zarbon1");
		createEntity(EntityZarbon2.class, 64, ModVars.MOD_ID + ".zarbon2");
		createEntity(EntityWhis.class, 64, ModVars.MOD_ID + ".whis");
		createEntity(EntityRaditz.class, 64, ModVars.MOD_ID + ".raditz");
		createEntity(EntityNappa.class, 64, ModVars.MOD_ID + ".nappa");
	}
	
	// simpleEntity
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public static void createEntity(Class entityClass, int trackingRange, String entityName)
	{
		int randomId = EntityRegistry.findGlobalUniqueEntityId();
		EntityRegistry.registerGlobalEntityID(entityClass, entityName, randomId);
		EntityRegistry.registerModEntity(entityClass, entityName, randomId, ModVars.MOD_ID, trackingRange, 1, true);
	}
}
