package hedaox.ninjinentities.rendering.entities;

import JinRyuu.DragonBC.common.Npcs.*;
import JinRyuu.DragonBC.common.Npcs.ModelRaditz;
import hedaox.ninjinentities.entities.*;
import hedaox.ninjinentities.entities.EntityFrost1;
import hedaox.ninjinentities.entities.EntityFrost3;
import hedaox.ninjinentities.entities.EntityFrost4;
import hedaox.ninjinentities.entities.EntityGoku2;
import hedaox.ninjinentities.entities.EntityGokuBlack;
import hedaox.ninjinentities.entities.EntityHit;
import hedaox.ninjinentities.entities.EntityMonaka;
import hedaox.ninjinentities.entities.EntityVegeta;
import hedaox.ninjinentities.entities.EntityVegeta2;
import hedaox.ninjinentities.entities.EntityVegeta3;
import hedaox.ninjinentities.entities.EntityVegetaCopy;
import hedaox.ninjinentities.entities.EntityWhis;
import hedaox.ninjinentities.entities.EntityZamasu;
import hedaox.ninjinentities.entities.EntityZarbon2;
import hedaox.ninjinentities.models.*;
import cpw.mods.fml.client.registry.RenderingRegistry;
import hedaox.ninjinentities.models.ModelNinjinRaditz;
import hedaox.ninjinentities.models.ModelVegeta;
import hedaox.ninjinentities.models.ModelWhis;
import hedaox.ninjinentities.models.ModelZamasu;

public class NinjinRenderEntities {
	public static void init()
	{
		RenderingRegistry.registerEntityRenderingHandler(EntityMasterBaba.class, new RenderDBC(new ModelBaba(1.0F,1.0F,1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBandit1.class, new RenderDBC(new ModelBandit1(1.2F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGeneralBlue.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityHercule.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanKid1.class, new RenderDBC(new ModelGohanKid1(0.55F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanKid2.class, new RenderDBC(new ModelGohanKid2(0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanKid3.class, new RenderDBC(new ModelGohanKid1(0.65F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanKidArmor.class, new RenderDBC(new ModelGohanKidArmor(0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanTeen.class, new RenderDBC(new ModelGohanTeen(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanTeenArmor.class, new RenderDBC(new ModelGohanTeen(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanTeenArmorSsj.class, new RenderDBC(new ModelGohanTeen(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanTeenSsj.class, new RenderDBC(new ModelGohanTeen(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanTeenSsj2.class, new RenderDBC(new ModelGohanTeenSsj2(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanAdult.class, new RenderDBC(new ModelGohanAdult(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanAdultSsj.class, new RenderDBC(new ModelGohanAdult(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanAdultSsj2.class, new RenderDBC(new ModelGohanAdultSsj2(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGohanUltimate.class, new RenderDBC(new ModelGohanAdultSsj2(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuKid1.class, new RenderDBC(new ModelGoku(0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuKid2.class, new RenderDBC(new ModelGoku(0.65F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoku1.class, new RenderDBC(new ModelGoku(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoku2.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoku2Kaioken.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuArmor.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuArmorSsj.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokunoweight.class, new RenderDBC(new ModelGoku(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSsj.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSsj2.class, new RenderDBC(new ModelGokuSsj2(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSsj3.class, new RenderDBC(new ModelGokuSsj3(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSsjg.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSsjb.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSuper.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSuperSsj.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuSuperSsjb.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuUI.class, new RenderDBC(new ModelGokuUi(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuUIM.class, new RenderDBC(new ModelGokuUi(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuYardrat.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuYardratSsj.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoten.class, new RenderDBC(new ModelGoku(0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGotenSsj.class, new RenderDBC(new ModelGokuSsj(0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGotenks.class, new RenderDBC(new ModelGotenks(0.75F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGotenksSsj.class, new RenderDBC(new ModelGotenks(0.75F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGotenksSsj3.class, new RenderDBC(new ModelGotenksSsj3(0.75F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKrillin1.class, new RenderDBC(new ModelNPCNormalScale(0.8F, 0.8F, 0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKrillin2.class, new RenderDBC(new ModelNPCNormalArmor(0.8F, 0.8F, 0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKrillinKid1.class, new RenderDBC(new ModelNPCNormalScale(0.575F, 0.575F, 0.575F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKrillinKid2.class, new RenderDBC(new ModelNPCNormalScale(0.625F, 0.625F, 0.625F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTien.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityChiaotzu1.class, new RenderDBC(new ModelNPCNormalScale(0.6F, 0.6F, 0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityChiaotzu2.class, new RenderDBC(new ModelNPCNormalScale(0.6F, 0.6F, 0.6F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityYamcha1.class, new RenderDBC(new ModelYamcha1(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityYamcha2.class, new RenderDBC(new ModelYamcha1(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityYamcha3.class, new RenderDBC(new ModelYamcha2(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityPiccolo.class, new RenderDBC(new ModelRaditz(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityOozaru.class, new RenderDBC(new ModelOozaru(2.3F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityRoshi.class, new RenderDBC(new ModelRoshi(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityRoshiBuff.class, new RenderDBC(new ModelNPCNormalScale(1.1F, 1.05F, 1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksArmor.class, new RenderDBC(new ModelTrunksArmor(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksArmorSsj.class, new RenderDBC(new ModelTrunksArmorSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksArmorSsjG2.class, new RenderDBC(new ModelTrunksArmorSsj(1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksArmorSsjG3.class, new RenderDBC(new ModelTrunksArmorSsjG3(1.2F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFutur.class, new RenderDBC(new ModelTrunks(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSsj.class, new RenderDBC(new ModelTrunksSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSuper.class, new RenderDBC(new ModelTrunks(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSuperSsj.class, new RenderDBC(new ModelTrunksSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSuperSsj2.class, new RenderDBC(new ModelTrunksSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSuperSsjG3.class, new RenderDBC(new ModelTrunksArmorSsjG3(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksFuturSuperSsjRage.class, new RenderDBC(new ModelTrunksSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksKid.class, new RenderDBC(new ModelTrunks(0.65F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrunksKidSsj.class, new RenderDBC(new ModelTrunksSsj(0.65F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeto.class, new RenderDBC(new ModelVegeto(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetoSsj.class, new RenderDBC(new ModelVegeto(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetoSsjb.class, new RenderDBC(new ModelVegeto(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGogeta.class, new RenderDBC(new ModelGogeta(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGogetaSsj.class, new RenderDBC(new ModelGogeta(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGogetaSsjb.class, new RenderDBC(new ModelGogeta(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta0.class, new RenderDBC(new ModelVegetaArmor(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta3.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSsj.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSsjG2.class, new RenderDBC(new ModelVegeta(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta2.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta2Ssj.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegeta2Ssj2.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSsjg.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSsjb.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSsjbe.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaMajin.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaOozaru.class, new RenderDBC(new ModelVegetaOozaru(2.3F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaCopy.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaBlueCopy.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSuper.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSuperSsj.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityVegetaSuperSsjb.class, new RenderDBC(new ModelVegeta(0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityCyborgTaopaipai.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityTaopaipai.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityDaimao.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityHit.class, new RenderDBC(new ModelNPCNormal(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityFrost1.class, new RenderDBC(new ModelRaditz(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityFrost3.class, new RenderDBC(new ModelRaditz(1.25F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityFrost4.class, new RenderDBC(new ModelRaditz(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityCaulifla.class, new RenderDBC(new ModelCaulifla(1, 0.7F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityCauliflaSsj.class, new RenderDBC(new ModelCaulifla(1, 0.7F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityCauliflaSsj2.class, new RenderDBC(new ModelCaulifla(2, 0.7F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKale.class, new RenderDBC(new ModelKale(0, 0.75F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaleSsj.class, new RenderDBC(new ModelKale(1, 0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaleSsjL.class, new RenderDBC(new ModelKale(2, 1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaleSsj2.class, new RenderDBC(new ModelKale(1, 0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMonaka.class, new RenderDBC(new ModelNPCNormalScale(0.7F, 0.7F, 0.7F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuBlack.class, new RenderDBC(new ModelGoku(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuBlackSsj.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityGokuBlackR.class, new RenderDBC(new ModelGokuSsj(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityZamasu.class, new RenderDBC(new ModelZamasu(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityZamasuMerged.class, new RenderDBC(new ModelZamasuMerged(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityJiren.class, new RenderDBC(new ModelJiren(1.1F, 1.1F, 1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityJirenSuperFullPower.class, new RenderDBC(new ModelJiren(1.15F, 1.15F, 1.15F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityToppo.class, new RenderDBC(new ModelToppo(1.2F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityToppoGOD.class, new RenderDBC(new ModelToppo(1.3F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityDyspo.class, new RenderDBC(new ModelDyspo(0.9F,1.0F,0.9F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKefla.class, new RenderDBC(new ModelKefla(0.775F,0), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityKeflaSsj.class, new RenderDBC(new ModelKefla(0.825F,1), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBergamo.class, new RenderDBC(new ModelTrioDanger(1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBasil.class, new RenderDBC(new ModelTrioDanger(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityLavender.class, new RenderDBC(new ModelTrioDanger(0.8F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityPilina.class, new RenderDBC(new ModelRaditz(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntitySaonel.class, new RenderDBC(new ModelRaditz(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBrolySuper.class, new RenderDBC(new ModelBroly(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBrolySuperWrath.class, new RenderDBC(new ModelBrolySsj(1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBrolySuperSsj.class, new RenderDBC(new ModelBrolySsj(1.1F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBrolySuperSsjL.class, new RenderDBC(new ModelBrolySsj(1.25F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityZarbon1.class, new RenderDBC(new ModelZarbon(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityZarbon2.class, new RenderDBC(new ModelZarbon(1.05F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityWhis.class, new RenderDBC(new ModelWhis(1.0F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityRaditz.class, new RenderDBC(new ModelNinjinRaditz(1.05F), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityNappa.class, new RenderDBC(new ModelNPCNormalArmor(1.125F,1.1F,1.125F), 0.5F));
	}
}
